# Generated by Django 5.2.1 on 2025-05-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_slug'),
    ]

    operations = [
    ]
